baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Mies Portfolio'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true